storage:
  image: tianon/true
  volumes:
    - /var/lib/registry
  command: "/true"

cache:
  image: redis
  restart: always

backend:
  image: registry:2
  restart: always
  ports:
    - 5000:5000
  links:
    - cache
    - storage
  volumes_from:
    - storage
  environment:
    SETTINGS_FLAVOR: local
    STORAGE_PATH: /var/lib/registry
    SEARCH_BACKEND: sqlalchemy
    CACHE_REDIS_HOST: cache
    CACHE_REDIS_PORT: 6379
    CACHE_LRU_REDIS_HOST: cache
    CACHE_LRU_REDIS_PORT: 6379

frontend:
  restart: always
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - 5080:80
  links:
    - backend
  environment:
    ENV_DOCKER_REGISTRY_HOST: backend
    ENV_DOCKER_REGISTRY_PORT: 5000
