swarmslave:
  build: jenkins-swarm-slave
  hostname: jenkins_swarm_slave_1
  # net: jenkins-network
  environment:
    - JENKINS_HOME=/home/jenkins_slave
    - JENKINS_LABELS=swarm
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/bin/docker
    - /tmp:/tmp
    - /usr/share/jenkins_slave:/usr/share/jenkins_slave
