jenkinsdata:
  build: jenkins-data

jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  ports:
    - "50000:50000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/bin/docker

jenkinsnginx:
  build: jenkins-nginx
  ports:
    - "80:80"
  links:
    - jenkinsmaster:jenkins-master
