data:
  build: jenkins-data

master:
  build: jenkins-master
  ports:
    - "50000:50000"
  volumes_from:
    - data

nginx:
  build: jenkins-nginx
  ports:
    - "80:80"
  links:
    - master:jenkins-master
